services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - DB_HOST=mysql
      - MYSQL_DATABASE=automation_taches
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - sonarnet

networks:
  sonarnet:
    external: true
volumes:
  mysql_data:
